# Default values for promtail-win.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: marcinwoloszz/promtail-win
  pullPolicy: Always
  tag: "3.1.0"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: "promtail-win"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
   windowsOptions:
     runAsUserName: "ContainerAdministrator"

securityContext:
   capabilities:
     drop:
     - ALL
   readOnlyRootFilesystem: true

service:
  type: ClusterIP
  port: 3101

resources:
  limits:
    cpu: 200m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector:
   kubernetes.io/os: windows

tolerations:
  - effect: NoSchedule
    key: usage-type
    operator: Equal
    value: windows

affinity: {}

configs:
  lokiURL: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
  positionsFileName: C:\promtail\positions.yaml
  listenPort: 3101
