name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - development

env:
  DOCKER_HUB_USERNAME: diquzart
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read version from file
        id: read-version
        run: |
          $version = Get-Content -Path Container/version
          echo "::set-output name=version::$version"

      - name: Print Promtail version
        run: |
          $version = $env:VERSION
          Write-Host "Promtail version: $version"

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Container/Containerfile
          build-args: PROMTAIL_VERSION=${{ steps.read-version.outputs.version }}
          tags: ${{ env.DOCKER_HUB_USERNAME }}/promtail-win:${{ steps.read-version.outputs.version }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Container/Containerfile
          push: ${{ env.DOCKER_HUB_USERNAME }}/promtail-win:${{ steps.read-version.outputs.version }}
